///////////////////////////////////////////////////////////
//  UtgaaendeJournalpost.cs
//  Implementation of the Class UtgaaendeJournalpost
//  Generated by Enterprise Architect
//  Created on:      27-mai-2020 09:36:24
//  Original author: TorKjetilNilsen
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FIKS.eMeldingArkiv.eMeldingForenkletArkiv;
namespace FIKS.eMeldingArkiv.eMeldingForenkletArkiv {
	public class UtgaaendeJournalpost {

		public KorrespondansepartIntern internAvsender;
		public Avskrivning avskrivning;
		public integer journalaar;
		public integer journalsekvensnummer;
		public integer journalpostnummer;
		public Journalstatus journalstatus;
		public date dokumentetsDato;
		/// <summary>
		/// Definisjon: Dato et internt produsert dokument ble sendt/ekspedert
		/// 
		/// Kilde: Registreres manuelt eller automatisk av systemet ved elektronisk
		/// kommunikasjon
		/// 
		/// Kommentar: (ingen)
		/// 
		/// M105 sendtDato
		/// </summary>
		public date sendtDato;
		public ForenkletDokument hoveddokument;
		/// <summary>
		/// Definisjon: Dato et internt produsert dokument ble sendt/ekspedert
		/// 
		/// Kilde: Registreres manuelt eller automatisk av systemet ved elektronisk
		/// kommunikasjon
		/// 
		/// Kommentar: (ingen)
		/// 
		/// M105 sendtDato
		/// </summary>
		public date offentlighetsvurdertDato;
		public EksternNøkkel referanseEksternNøkkel;
		public string tittel;
		public FIKS.eMeldingArkiv.eMeldingForenkletArkiv.ForenkletDokument vedlegg;
		public FIKS.eMeldingArkiv.eMeldingForenkletArkiv.Korrespondansepart eksternMottaker;

		public UtgaaendeJournalpost(){

		}

		~UtgaaendeJournalpost(){

		}

	}//end UtgaaendeJournalpost

}//end namespace eMeldingForenkletArkiv