//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:4.0.30319.42000
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace no.ks.fiks.io.arkivmelding {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding", IsNullable=false)]
    public partial class arkivmelding {
        
        private string systemField;
        
        private string meldingIdField;
        
        private System.DateTime tidspunktField;
        
        private int antallFilerField;
        
        private object[] itemsField;
        
        private string[] textField;
        
        /// <remarks/>
        public string system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
        
        /// <remarks/>
        public string meldingId {
            get {
                return this.meldingIdField;
            }
            set {
                this.meldingIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime tidspunkt {
            get {
                return this.tidspunktField;
            }
            set {
                this.tidspunktField = value;
            }
        }
        
        /// <remarks/>
        public int antallFiler {
            get {
                return this.antallFilerField;
            }
            set {
                this.antallFilerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("basisregistrering", typeof(basisregistrering))]
        [System.Xml.Serialization.XmlElementAttribute("mappe", typeof(mappe))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(journalpost))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding")]
    public partial class basisregistrering : registrering {
        
        private string tittelField;
        
        private string offentligTittelField;
        
        private string beskrivelseField;
        
        private string[] noekkelordField;
        
        private string[] forfatterField;
        
        private dokumentmedium dokumentmediumField;
        
        private bool dokumentmediumFieldSpecified;
        
        private string[] oppbevaringsstedField;
        
        private object virksomhetsspesifikkeMetadataField;
        
        private merknad[] merknadField;
        
        private kryssreferanse[] kryssreferanseField;
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        public string offentligTittel {
            get {
                return this.offentligTittelField;
            }
            set {
                this.offentligTittelField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("noekkelord")]
        public string[] noekkelord {
            get {
                return this.noekkelordField;
            }
            set {
                this.noekkelordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("forfatter")]
        public string[] forfatter {
            get {
                return this.forfatterField;
            }
            set {
                this.forfatterField = value;
            }
        }
        
        /// <remarks/>
        public dokumentmedium dokumentmedium {
            get {
                return this.dokumentmediumField;
            }
            set {
                this.dokumentmediumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dokumentmediumSpecified {
            get {
                return this.dokumentmediumFieldSpecified;
            }
            set {
                this.dokumentmediumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("oppbevaringssted")]
        public string[] oppbevaringssted {
            get {
                return this.oppbevaringsstedField;
            }
            set {
                this.oppbevaringsstedField = value;
            }
        }
        
        /// <remarks/>
        public object virksomhetsspesifikkeMetadata {
            get {
                return this.virksomhetsspesifikkeMetadataField;
            }
            set {
                this.virksomhetsspesifikkeMetadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("merknad")]
        public merknad[] merknad {
            get {
                return this.merknadField;
            }
            set {
                this.merknadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("kryssreferanse")]
        public kryssreferanse[] kryssreferanse {
            get {
                return this.kryssreferanseField;
            }
            set {
                this.kryssreferanseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog")]
    public enum dokumentmedium {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Fysisk medium")]
        Fysiskmedium,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Elektronisk arkiv")]
        Elektroniskarkiv,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Blandet fysisk og elektronisk arkiv")]
        Blandetfysiskogelektroniskarkiv,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding")]
    public partial class klasse {
        
        private string systemIDField;
        
        private string klasseIDField;
        
        private string tittelField;
        
        private string beskrivelseField;
        
        private string[] noekkelordField;
        
        private System.DateTime opprettetDatoField;
        
        private string opprettetAvField;
        
        /// <remarks/>
        public string systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public string klasseID {
            get {
                return this.klasseIDField;
            }
            set {
                this.klasseIDField = value;
            }
        }
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("noekkelord")]
        public string[] noekkelord {
            get {
                return this.noekkelordField;
            }
            set {
                this.noekkelordField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding")]
    public partial class klassifikasjon {
        
        private string referanseKlassifikasjonssystemField;
        
        private string klasseIDField;
        
        private string tittelField;
        
        private string beskrivelseField;
        
        private string[] noekkelordField;
        
        private System.DateTime opprettetDatoField;
        
        private bool opprettetDatoFieldSpecified;
        
        private string opprettetAvField;
        
        /// <remarks/>
        public string referanseKlassifikasjonssystem {
            get {
                return this.referanseKlassifikasjonssystemField;
            }
            set {
                this.referanseKlassifikasjonssystemField = value;
            }
        }
        
        /// <remarks/>
        public string klasseID {
            get {
                return this.klasseIDField;
            }
            set {
                this.klasseIDField = value;
            }
        }
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("noekkelord")]
        public string[] noekkelord {
            get {
                return this.noekkelordField;
            }
            set {
                this.noekkelordField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opprettetDatoSpecified {
            get {
                return this.opprettetDatoFieldSpecified;
            }
            set {
                this.opprettetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding")]
    public partial class presedens {
        
        private System.DateTime presedensDatoField;
        
        private System.DateTime opprettetDatoField;
        
        private string opprettetAvField;
        
        private string tittelField;
        
        private string beskrivelseField;
        
        private string presedensHjemmelField;
        
        private string rettskildefaktorField;
        
        private System.DateTime presedensGodkjentDatoField;
        
        private bool presedensGodkjentDatoFieldSpecified;
        
        private string presedensGodkjentAvField;
        
        private System.DateTime avsluttetDatoField;
        
        private bool avsluttetDatoFieldSpecified;
        
        private string avsluttetAvField;
        
        private presedensstatus presedensStatusField;
        
        private bool presedensStatusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime presedensDato {
            get {
                return this.presedensDatoField;
            }
            set {
                this.presedensDatoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        public string presedensHjemmel {
            get {
                return this.presedensHjemmelField;
            }
            set {
                this.presedensHjemmelField = value;
            }
        }
        
        /// <remarks/>
        public string rettskildefaktor {
            get {
                return this.rettskildefaktorField;
            }
            set {
                this.rettskildefaktorField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime presedensGodkjentDato {
            get {
                return this.presedensGodkjentDatoField;
            }
            set {
                this.presedensGodkjentDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool presedensGodkjentDatoSpecified {
            get {
                return this.presedensGodkjentDatoFieldSpecified;
            }
            set {
                this.presedensGodkjentDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string presedensGodkjentAv {
            get {
                return this.presedensGodkjentAvField;
            }
            set {
                this.presedensGodkjentAvField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime avsluttetDato {
            get {
                return this.avsluttetDatoField;
            }
            set {
                this.avsluttetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avsluttetDatoSpecified {
            get {
                return this.avsluttetDatoFieldSpecified;
            }
            set {
                this.avsluttetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string avsluttetAv {
            get {
                return this.avsluttetAvField;
            }
            set {
                this.avsluttetAvField = value;
            }
        }
        
        /// <remarks/>
        public presedensstatus presedensStatus {
            get {
                return this.presedensStatusField;
            }
            set {
                this.presedensStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool presedensStatusSpecified {
            get {
                return this.presedensStatusFieldSpecified;
            }
            set {
                this.presedensStatusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog")]
    public enum presedensstatus {
        
        /// <remarks/>
        Gjeldende,
        
        /// <remarks/>
        Foreldet,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding")]
    public partial class dokumentflyt {
        
        private string flytTilField;
        
        private string flytFraField;
        
        private System.DateTime flytMottattDatoField;
        
        private System.DateTime flytSendtDatoField;
        
        private string flytStatusField;
        
        private string flytMerknadField;
        
        /// <remarks/>
        public string flytTil {
            get {
                return this.flytTilField;
            }
            set {
                this.flytTilField = value;
            }
        }
        
        /// <remarks/>
        public string flytFra {
            get {
                return this.flytFraField;
            }
            set {
                this.flytFraField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime flytMottattDato {
            get {
                return this.flytMottattDatoField;
            }
            set {
                this.flytMottattDatoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime flytSendtDato {
            get {
                return this.flytSendtDatoField;
            }
            set {
                this.flytSendtDatoField = value;
            }
        }
        
        /// <remarks/>
        public string flytStatus {
            get {
                return this.flytStatusField;
            }
            set {
                this.flytStatusField = value;
            }
        }
        
        /// <remarks/>
        public string flytMerknad {
            get {
                return this.flytMerknadField;
            }
            set {
                this.flytMerknadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding")]
    public partial class avskrivning {
        
        private System.DateTime avskrivningsdatoField;
        
        private string avskrevetAvField;
        
        private avskrivningsmaate avskrivningsmaateField;
        
        private string referanseAvskrivesAvJournalpostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime avskrivningsdato {
            get {
                return this.avskrivningsdatoField;
            }
            set {
                this.avskrivningsdatoField = value;
            }
        }
        
        /// <remarks/>
        public string avskrevetAv {
            get {
                return this.avskrevetAvField;
            }
            set {
                this.avskrevetAvField = value;
            }
        }
        
        /// <remarks/>
        public avskrivningsmaate avskrivningsmaate {
            get {
                return this.avskrivningsmaateField;
            }
            set {
                this.avskrivningsmaateField = value;
            }
        }
        
        /// <remarks/>
        public string referanseAvskrivesAvJournalpost {
            get {
                return this.referanseAvskrivesAvJournalpostField;
            }
            set {
                this.referanseAvskrivesAvJournalpostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog")]
    public enum avskrivningsmaate {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Besvart med brev")]
        Besvartmedbrev,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Besvart med e-post")]
        Besvartmedepost,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Besvart på telefon")]
        Besvartpåtelefon,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Tatt til etterretning")]
        Tatttiletterretning,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Tatt til orientering")]
        Tatttilorientering,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding")]
    public partial class korrespondansepart {
        
        private korrespondanseparttype korrespondanseparttypeField;
        
        private string korrespondansepartNavnField;
        
        private string[] postadresseField;
        
        private string postnummerField;
        
        private string poststedField;
        
        private string landField;
        
        private string epostadresseField;
        
        private string[] telefonnummerField;
        
        private string kontaktpersonField;
        
        private string administrativEnhetField;
        
        private string saksbehandlerField;
        
        /// <remarks/>
        public korrespondanseparttype korrespondanseparttype {
            get {
                return this.korrespondanseparttypeField;
            }
            set {
                this.korrespondanseparttypeField = value;
            }
        }
        
        /// <remarks/>
        public string korrespondansepartNavn {
            get {
                return this.korrespondansepartNavnField;
            }
            set {
                this.korrespondansepartNavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("postadresse")]
        public string[] postadresse {
            get {
                return this.postadresseField;
            }
            set {
                this.postadresseField = value;
            }
        }
        
        /// <remarks/>
        public string postnummer {
            get {
                return this.postnummerField;
            }
            set {
                this.postnummerField = value;
            }
        }
        
        /// <remarks/>
        public string poststed {
            get {
                return this.poststedField;
            }
            set {
                this.poststedField = value;
            }
        }
        
        /// <remarks/>
        public string land {
            get {
                return this.landField;
            }
            set {
                this.landField = value;
            }
        }
        
        /// <remarks/>
        public string epostadresse {
            get {
                return this.epostadresseField;
            }
            set {
                this.epostadresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("telefonnummer")]
        public string[] telefonnummer {
            get {
                return this.telefonnummerField;
            }
            set {
                this.telefonnummerField = value;
            }
        }
        
        /// <remarks/>
        public string kontaktperson {
            get {
                return this.kontaktpersonField;
            }
            set {
                this.kontaktpersonField = value;
            }
        }
        
        /// <remarks/>
        public string administrativEnhet {
            get {
                return this.administrativEnhetField;
            }
            set {
                this.administrativEnhetField = value;
            }
        }
        
        /// <remarks/>
        public string saksbehandler {
            get {
                return this.saksbehandlerField;
            }
            set {
                this.saksbehandlerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog")]
    public enum korrespondanseparttype {
        
        /// <remarks/>
        Avsender,
        
        /// <remarks/>
        Mottaker,
        
        /// <remarks/>
        Kopimottaker,
        
        /// <remarks/>
        Gruppemottaker,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intern avsender")]
        Internavsender,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intern mottaker")]
        Internmottaker,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding")]
    public partial class kryssreferanse {
        
        private string referanseTilKlasseField;
        
        private string referanseTilMappeField;
        
        private string referanseTilRegistreringField;
        
        /// <remarks/>
        public string referanseTilKlasse {
            get {
                return this.referanseTilKlasseField;
            }
            set {
                this.referanseTilKlasseField = value;
            }
        }
        
        /// <remarks/>
        public string referanseTilMappe {
            get {
                return this.referanseTilMappeField;
            }
            set {
                this.referanseTilMappeField = value;
            }
        }
        
        /// <remarks/>
        public string referanseTilRegistrering {
            get {
                return this.referanseTilRegistreringField;
            }
            set {
                this.referanseTilRegistreringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding")]
    public partial class dokumentobjekt {
        
        private string versjonsnummerField;
        
        private variantformat variantformatField;
        
        private System.DateTime opprettetDatoField;
        
        private string opprettetAvField;
        
        private string referanseDokumentfilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string versjonsnummer {
            get {
                return this.versjonsnummerField;
            }
            set {
                this.versjonsnummerField = value;
            }
        }
        
        /// <remarks/>
        public variantformat variantformat {
            get {
                return this.variantformatField;
            }
            set {
                this.variantformatField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        public string referanseDokumentfil {
            get {
                return this.referanseDokumentfilField;
            }
            set {
                this.referanseDokumentfilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog")]
    public enum variantformat {
        
        /// <remarks/>
        Produksjonsformat,
        
        /// <remarks/>
        Arkivformat,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Dokument hvor deler av innholdet er skjermet")]
        Dokumenthvordeleravinnholdeterskjermet,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding")]
    public partial class merknad {
        
        private string merknadstekstField;
        
        private string merknadstypeField;
        
        private System.DateTime merknadsdatoField;
        
        private string merknadRegistrertAvField;
        
        /// <remarks/>
        public string merknadstekst {
            get {
                return this.merknadstekstField;
            }
            set {
                this.merknadstekstField = value;
            }
        }
        
        /// <remarks/>
        public string merknadstype {
            get {
                return this.merknadstypeField;
            }
            set {
                this.merknadstypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime merknadsdato {
            get {
                return this.merknadsdatoField;
            }
            set {
                this.merknadsdatoField = value;
            }
        }
        
        /// <remarks/>
        public string merknadRegistrertAv {
            get {
                return this.merknadRegistrertAvField;
            }
            set {
                this.merknadRegistrertAvField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding")]
    public partial class dokumentbeskrivelse {
        
        private string systemIDField;
        
        private string dokumenttypeField;
        
        private dokumentstatus dokumentstatusField;
        
        private string tittelField;
        
        private string beskrivelseField;
        
        private string[] forfatterField;
        
        private System.DateTime opprettetDatoField;
        
        private string opprettetAvField;
        
        private dokumentmedium dokumentmediumField;
        
        private bool dokumentmediumFieldSpecified;
        
        private string oppbevaringsstedField;
        
        private string[] referanseArkivdelField;
        
        private tilknyttetRegistreringSom tilknyttetRegistreringSomField;
        
        private string dokumentnummerField;
        
        private System.DateTime tilknyttetDatoField;
        
        private string tilknyttetAvField;
        
        private merknad[] merknadField;
        
        private skjerming skjermingField;
        
        private gradering graderingField;
        
        private dokumentobjekt[] dokumentobjektField;
        
        /// <remarks/>
        public string systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public string dokumenttype {
            get {
                return this.dokumenttypeField;
            }
            set {
                this.dokumenttypeField = value;
            }
        }
        
        /// <remarks/>
        public dokumentstatus dokumentstatus {
            get {
                return this.dokumentstatusField;
            }
            set {
                this.dokumentstatusField = value;
            }
        }
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("forfatter")]
        public string[] forfatter {
            get {
                return this.forfatterField;
            }
            set {
                this.forfatterField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        public dokumentmedium dokumentmedium {
            get {
                return this.dokumentmediumField;
            }
            set {
                this.dokumentmediumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dokumentmediumSpecified {
            get {
                return this.dokumentmediumFieldSpecified;
            }
            set {
                this.dokumentmediumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string oppbevaringssted {
            get {
                return this.oppbevaringsstedField;
            }
            set {
                this.oppbevaringsstedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referanseArkivdel")]
        public string[] referanseArkivdel {
            get {
                return this.referanseArkivdelField;
            }
            set {
                this.referanseArkivdelField = value;
            }
        }
        
        /// <remarks/>
        public tilknyttetRegistreringSom tilknyttetRegistreringSom {
            get {
                return this.tilknyttetRegistreringSomField;
            }
            set {
                this.tilknyttetRegistreringSomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string dokumentnummer {
            get {
                return this.dokumentnummerField;
            }
            set {
                this.dokumentnummerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime tilknyttetDato {
            get {
                return this.tilknyttetDatoField;
            }
            set {
                this.tilknyttetDatoField = value;
            }
        }
        
        /// <remarks/>
        public string tilknyttetAv {
            get {
                return this.tilknyttetAvField;
            }
            set {
                this.tilknyttetAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("merknad")]
        public merknad[] merknad {
            get {
                return this.merknadField;
            }
            set {
                this.merknadField = value;
            }
        }
        
        /// <remarks/>
        public skjerming skjerming {
            get {
                return this.skjermingField;
            }
            set {
                this.skjermingField = value;
            }
        }
        
        /// <remarks/>
        public gradering gradering {
            get {
                return this.graderingField;
            }
            set {
                this.graderingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dokumentobjekt")]
        public dokumentobjekt[] dokumentobjekt {
            get {
                return this.dokumentobjektField;
            }
            set {
                this.dokumentobjektField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog")]
    public enum dokumentstatus {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Dokumentet er under redigering")]
        Dokumenteterunderredigering,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Dokumentet er ferdigstilt")]
        Dokumenteterferdigstilt,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog")]
    public enum tilknyttetRegistreringSom {
        
        /// <remarks/>
        Hoveddokument,
        
        /// <remarks/>
        Vedlegg,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding")]
    public partial class skjerming {
        
        private string tilgangsrestriksjonField;
        
        private string skjermingshjemmelField;
        
        private string[] skjermingMetadataField;
        
        private skjermingDokument skjermingDokumentField;
        
        private bool skjermingDokumentFieldSpecified;
        
        private string skjermingsvarighetField;
        
        private System.DateTime skjermingOpphoererDatoField;
        
        private bool skjermingOpphoererDatoFieldSpecified;
        
        /// <remarks/>
        public string tilgangsrestriksjon {
            get {
                return this.tilgangsrestriksjonField;
            }
            set {
                this.tilgangsrestriksjonField = value;
            }
        }
        
        /// <remarks/>
        public string skjermingshjemmel {
            get {
                return this.skjermingshjemmelField;
            }
            set {
                this.skjermingshjemmelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("skjermingMetadata")]
        public string[] skjermingMetadata {
            get {
                return this.skjermingMetadataField;
            }
            set {
                this.skjermingMetadataField = value;
            }
        }
        
        /// <remarks/>
        public skjermingDokument skjermingDokument {
            get {
                return this.skjermingDokumentField;
            }
            set {
                this.skjermingDokumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool skjermingDokumentSpecified {
            get {
                return this.skjermingDokumentFieldSpecified;
            }
            set {
                this.skjermingDokumentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string skjermingsvarighet {
            get {
                return this.skjermingsvarighetField;
            }
            set {
                this.skjermingsvarighetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime skjermingOpphoererDato {
            get {
                return this.skjermingOpphoererDatoField;
            }
            set {
                this.skjermingOpphoererDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool skjermingOpphoererDatoSpecified {
            get {
                return this.skjermingOpphoererDatoFieldSpecified;
            }
            set {
                this.skjermingOpphoererDatoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog")]
    public enum skjermingDokument {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Skjerming av hele dokumentet")]
        Skjermingavheledokumentet,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Skjerming av deler av dokumentet")]
        Skjermingavdeleravdokumentet,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding")]
    public partial class gradering {
        
        private gradering1 gradering1Field;
        
        private System.DateTime graderingsdatoField;
        
        private string gradertAvField;
        
        private System.DateTime nedgraderingsdatoField;
        
        private bool nedgraderingsdatoFieldSpecified;
        
        private string nedgradertAvField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gradering")]
        public gradering1 gradering1 {
            get {
                return this.gradering1Field;
            }
            set {
                this.gradering1Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime graderingsdato {
            get {
                return this.graderingsdatoField;
            }
            set {
                this.graderingsdatoField = value;
            }
        }
        
        /// <remarks/>
        public string gradertAv {
            get {
                return this.gradertAvField;
            }
            set {
                this.gradertAvField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime nedgraderingsdato {
            get {
                return this.nedgraderingsdatoField;
            }
            set {
                this.nedgraderingsdatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nedgraderingsdatoSpecified {
            get {
                return this.nedgraderingsdatoFieldSpecified;
            }
            set {
                this.nedgraderingsdatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string nedgradertAv {
            get {
                return this.nedgradertAvField;
            }
            set {
                this.nedgradertAvField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="gradering", Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog")]
    public enum gradering1 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Strengt hemmelig (sikkerhetsgrad)")]
        Strengthemmeligsikkerhetsgrad,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Hemmelig (sikkerhetsgrad)")]
        Hemmeligsikkerhetsgrad,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Konfidensielt (sikkerhetsgrad)")]
        Konfidensieltsikkerhetsgrad,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Begrenset (sikkerhetsgrad)")]
        Begrensetsikkerhetsgrad,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Fortrolig (beskyttelsesgrad)")]
        Fortroligbeskyttelsesgrad,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Strengt fortrolig (beskyttelsesgrad)")]
        Strengtfortroligbeskyttelsesgrad,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(basisregistrering))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(journalpost))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding")]
    public partial class registrering {
        
        private string systemIDField;
        
        private System.DateTime opprettetDatoField;
        
        private string opprettetAvField;
        
        private System.DateTime arkivertDatoField;
        
        private bool arkivertDatoFieldSpecified;
        
        private string arkivertAvField;
        
        private string registreringsIDField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private skjerming skjermingField;
        
        private gradering graderingField;
        
        private dokumentbeskrivelse[] dokumentbeskrivelseField;
        
        private dokumentobjekt[] dokumentobjektField;
        
        /// <remarks/>
        public string systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime arkivertDato {
            get {
                return this.arkivertDatoField;
            }
            set {
                this.arkivertDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arkivertDatoSpecified {
            get {
                return this.arkivertDatoFieldSpecified;
            }
            set {
                this.arkivertDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string arkivertAv {
            get {
                return this.arkivertAvField;
            }
            set {
                this.arkivertAvField = value;
            }
        }
        
        /// <remarks/>
        public string registreringsID {
            get {
                return this.registreringsIDField;
            }
            set {
                this.registreringsIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referanseArkivdel", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("referanseForelderMappe", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("referanseKlasse", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        public skjerming skjerming {
            get {
                return this.skjermingField;
            }
            set {
                this.skjermingField = value;
            }
        }
        
        /// <remarks/>
        public gradering gradering {
            get {
                return this.graderingField;
            }
            set {
                this.graderingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dokumentbeskrivelse")]
        public dokumentbeskrivelse[] dokumentbeskrivelse {
            get {
                return this.dokumentbeskrivelseField;
            }
            set {
                this.dokumentbeskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dokumentobjekt")]
        public dokumentobjekt[] dokumentobjekt {
            get {
                return this.dokumentobjektField;
            }
            set {
                this.dokumentobjektField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        referanseArkivdel,
        
        /// <remarks/>
        referanseForelderMappe,
        
        /// <remarks/>
        referanseKlasse,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding")]
    public partial class sakspart {
        
        private string sakspartIDField;
        
        private string sakspartNavnField;
        
        private string sakspartRolleField;
        
        private string[] postadresseField;
        
        private string postnummerField;
        
        private string poststedField;
        
        private string landField;
        
        private string epostadresseField;
        
        private string[] telefonnummerField;
        
        private string kontaktpersonField;
        
        private object virksomhetsspesifikkeMetadataField;
        
        /// <remarks/>
        public string sakspartID {
            get {
                return this.sakspartIDField;
            }
            set {
                this.sakspartIDField = value;
            }
        }
        
        /// <remarks/>
        public string sakspartNavn {
            get {
                return this.sakspartNavnField;
            }
            set {
                this.sakspartNavnField = value;
            }
        }
        
        /// <remarks/>
        public string sakspartRolle {
            get {
                return this.sakspartRolleField;
            }
            set {
                this.sakspartRolleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("postadresse")]
        public string[] postadresse {
            get {
                return this.postadresseField;
            }
            set {
                this.postadresseField = value;
            }
        }
        
        /// <remarks/>
        public string postnummer {
            get {
                return this.postnummerField;
            }
            set {
                this.postnummerField = value;
            }
        }
        
        /// <remarks/>
        public string poststed {
            get {
                return this.poststedField;
            }
            set {
                this.poststedField = value;
            }
        }
        
        /// <remarks/>
        public string land {
            get {
                return this.landField;
            }
            set {
                this.landField = value;
            }
        }
        
        /// <remarks/>
        public string epostadresse {
            get {
                return this.epostadresseField;
            }
            set {
                this.epostadresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("telefonnummer")]
        public string[] telefonnummer {
            get {
                return this.telefonnummerField;
            }
            set {
                this.telefonnummerField = value;
            }
        }
        
        /// <remarks/>
        public string kontaktperson {
            get {
                return this.kontaktpersonField;
            }
            set {
                this.kontaktpersonField = value;
            }
        }
        
        /// <remarks/>
        public object virksomhetsspesifikkeMetadata {
            get {
                return this.virksomhetsspesifikkeMetadataField;
            }
            set {
                this.virksomhetsspesifikkeMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(saksmappe))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding")]
    public partial class mappe {
        
        private string systemIDField;
        
        private string mappeIDField;
        
        private string referanseForeldermappeField;
        
        private string tittelField;
        
        private string offentligTittelField;
        
        private string beskrivelseField;
        
        private string[] noekkelordField;
        
        private dokumentmedium dokumentmediumField;
        
        private bool dokumentmediumFieldSpecified;
        
        private string[] oppbevaringsstedField;
        
        private System.DateTime opprettetDatoField;
        
        private string opprettetAvField;
        
        private System.DateTime avsluttetDatoField;
        
        private bool avsluttetDatoFieldSpecified;
        
        private string avsluttetAvField;
        
        private string[] referanseArkivdelField;
        
        private object virksomhetsspesifikkeMetadataField;
        
        private kryssreferanse[] kryssreferanseField;
        
        private merknad[] merknadField;
        
        private skjerming skjermingField;
        
        private gradering graderingField;
        
        private klassifikasjon[] klassifikasjonField;
        
        private object[] itemsField;
        
        /// <remarks/>
        public string systemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public string mappeID {
            get {
                return this.mappeIDField;
            }
            set {
                this.mappeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReferanseForeldermappe {
            get {
                return this.referanseForeldermappeField;
            }
            set {
                this.referanseForeldermappeField = value;
            }
        }
        
        /// <remarks/>
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        public string offentligTittel {
            get {
                return this.offentligTittelField;
            }
            set {
                this.offentligTittelField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("noekkelord")]
        public string[] noekkelord {
            get {
                return this.noekkelordField;
            }
            set {
                this.noekkelordField = value;
            }
        }
        
        /// <remarks/>
        public dokumentmedium dokumentmedium {
            get {
                return this.dokumentmediumField;
            }
            set {
                this.dokumentmediumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dokumentmediumSpecified {
            get {
                return this.dokumentmediumFieldSpecified;
            }
            set {
                this.dokumentmediumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("oppbevaringssted")]
        public string[] oppbevaringssted {
            get {
                return this.oppbevaringsstedField;
            }
            set {
                this.oppbevaringsstedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime opprettetDato {
            get {
                return this.opprettetDatoField;
            }
            set {
                this.opprettetDatoField = value;
            }
        }
        
        /// <remarks/>
        public string opprettetAv {
            get {
                return this.opprettetAvField;
            }
            set {
                this.opprettetAvField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime avsluttetDato {
            get {
                return this.avsluttetDatoField;
            }
            set {
                this.avsluttetDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avsluttetDatoSpecified {
            get {
                return this.avsluttetDatoFieldSpecified;
            }
            set {
                this.avsluttetDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string avsluttetAv {
            get {
                return this.avsluttetAvField;
            }
            set {
                this.avsluttetAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referanseArkivdel")]
        public string[] referanseArkivdel {
            get {
                return this.referanseArkivdelField;
            }
            set {
                this.referanseArkivdelField = value;
            }
        }
        
        /// <remarks/>
        public object virksomhetsspesifikkeMetadata {
            get {
                return this.virksomhetsspesifikkeMetadataField;
            }
            set {
                this.virksomhetsspesifikkeMetadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("kryssreferanse")]
        public kryssreferanse[] kryssreferanse {
            get {
                return this.kryssreferanseField;
            }
            set {
                this.kryssreferanseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("merknad")]
        public merknad[] merknad {
            get {
                return this.merknadField;
            }
            set {
                this.merknadField = value;
            }
        }
        
        /// <remarks/>
        public skjerming skjerming {
            get {
                return this.skjermingField;
            }
            set {
                this.skjermingField = value;
            }
        }
        
        /// <remarks/>
        public gradering gradering {
            get {
                return this.graderingField;
            }
            set {
                this.graderingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("klassifikasjon")]
        public klassifikasjon[] klassifikasjon {
            get {
                return this.klassifikasjonField;
            }
            set {
                this.klassifikasjonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("basisregistrering", typeof(basisregistrering))]
        [System.Xml.Serialization.XmlElementAttribute("mappe", typeof(mappe))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding")]
    public partial class saksmappe : mappe {
        
        private System.DateTime saksdatoField;
        
        private string administrativEnhetField;
        
        private string saksansvarligField;
        
        private string journalenhetField;
        
        private saksstatus saksstatusField;
        
        private string[] referanseSekundaerKlassifikasjonField;
        
        private sakspart[] sakspartField;
        
        private presedens[] presedensField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime saksdato {
            get {
                return this.saksdatoField;
            }
            set {
                this.saksdatoField = value;
            }
        }
        
        /// <remarks/>
        public string administrativEnhet {
            get {
                return this.administrativEnhetField;
            }
            set {
                this.administrativEnhetField = value;
            }
        }
        
        /// <remarks/>
        public string saksansvarlig {
            get {
                return this.saksansvarligField;
            }
            set {
                this.saksansvarligField = value;
            }
        }
        
        /// <remarks/>
        public string journalenhet {
            get {
                return this.journalenhetField;
            }
            set {
                this.journalenhetField = value;
            }
        }
        
        /// <remarks/>
        public saksstatus saksstatus {
            get {
                return this.saksstatusField;
            }
            set {
                this.saksstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referanseSekundaerKlassifikasjon")]
        public string[] referanseSekundaerKlassifikasjon {
            get {
                return this.referanseSekundaerKlassifikasjonField;
            }
            set {
                this.referanseSekundaerKlassifikasjonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sakspart")]
        public sakspart[] sakspart {
            get {
                return this.sakspartField;
            }
            set {
                this.sakspartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("presedens")]
        public presedens[] presedens {
            get {
                return this.presedensField;
            }
            set {
                this.presedensField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog")]
    public enum saksstatus {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Under behandling")]
        Underbehandling,
        
        /// <remarks/>
        Avsluttet,
        
        /// <remarks/>
        Utgår,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/arkivmelding")]
    public partial class journalpost : basisregistrering {
        
        private string journalaarField;
        
        private string journalsekvensnummerField;
        
        private string journalpostnummerField;
        
        private journalposttype journalposttypeField;
        
        private journalstatus journalstatusField;
        
        private System.DateTime journaldatoField;
        
        private System.DateTime dokumentetsDatoField;
        
        private bool dokumentetsDatoFieldSpecified;
        
        private System.DateTime mottattDatoField;
        
        private bool mottattDatoFieldSpecified;
        
        private System.DateTime sendtDatoField;
        
        private bool sendtDatoFieldSpecified;
        
        private System.DateTime forfallsdatoField;
        
        private bool forfallsdatoFieldSpecified;
        
        private System.DateTime offentlighetsvurdertDatoField;
        
        private bool offentlighetsvurdertDatoFieldSpecified;
        
        private string antallVedleggField;
        
        private System.DateTime utlaantDatoField;
        
        private bool utlaantDatoFieldSpecified;
        
        private string utlaantTilField;
        
        private string journalenhetField;
        
        private korrespondansepart[] korrespondansepartField;
        
        private avskrivning[] avskrivningField;
        
        private dokumentflyt[] dokumentflytField;
        
        private presedens[] presedensField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string journalaar {
            get {
                return this.journalaarField;
            }
            set {
                this.journalaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string journalsekvensnummer {
            get {
                return this.journalsekvensnummerField;
            }
            set {
                this.journalsekvensnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string journalpostnummer {
            get {
                return this.journalpostnummerField;
            }
            set {
                this.journalpostnummerField = value;
            }
        }
        
        /// <remarks/>
        public journalposttype journalposttype {
            get {
                return this.journalposttypeField;
            }
            set {
                this.journalposttypeField = value;
            }
        }
        
        /// <remarks/>
        public journalstatus journalstatus {
            get {
                return this.journalstatusField;
            }
            set {
                this.journalstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime journaldato {
            get {
                return this.journaldatoField;
            }
            set {
                this.journaldatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dokumentetsDato {
            get {
                return this.dokumentetsDatoField;
            }
            set {
                this.dokumentetsDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dokumentetsDatoSpecified {
            get {
                return this.dokumentetsDatoFieldSpecified;
            }
            set {
                this.dokumentetsDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime mottattDato {
            get {
                return this.mottattDatoField;
            }
            set {
                this.mottattDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mottattDatoSpecified {
            get {
                return this.mottattDatoFieldSpecified;
            }
            set {
                this.mottattDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime sendtDato {
            get {
                return this.sendtDatoField;
            }
            set {
                this.sendtDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sendtDatoSpecified {
            get {
                return this.sendtDatoFieldSpecified;
            }
            set {
                this.sendtDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime forfallsdato {
            get {
                return this.forfallsdatoField;
            }
            set {
                this.forfallsdatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool forfallsdatoSpecified {
            get {
                return this.forfallsdatoFieldSpecified;
            }
            set {
                this.forfallsdatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime offentlighetsvurdertDato {
            get {
                return this.offentlighetsvurdertDatoField;
            }
            set {
                this.offentlighetsvurdertDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool offentlighetsvurdertDatoSpecified {
            get {
                return this.offentlighetsvurdertDatoFieldSpecified;
            }
            set {
                this.offentlighetsvurdertDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string antallVedlegg {
            get {
                return this.antallVedleggField;
            }
            set {
                this.antallVedleggField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime utlaantDato {
            get {
                return this.utlaantDatoField;
            }
            set {
                this.utlaantDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool utlaantDatoSpecified {
            get {
                return this.utlaantDatoFieldSpecified;
            }
            set {
                this.utlaantDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string utlaantTil {
            get {
                return this.utlaantTilField;
            }
            set {
                this.utlaantTilField = value;
            }
        }
        
        /// <remarks/>
        public string journalenhet {
            get {
                return this.journalenhetField;
            }
            set {
                this.journalenhetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("korrespondansepart")]
        public korrespondansepart[] korrespondansepart {
            get {
                return this.korrespondansepartField;
            }
            set {
                this.korrespondansepartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("avskrivning")]
        public avskrivning[] avskrivning {
            get {
                return this.avskrivningField;
            }
            set {
                this.avskrivningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dokumentflyt")]
        public dokumentflyt[] dokumentflyt {
            get {
                return this.dokumentflytField;
            }
            set {
                this.dokumentflytField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("presedens")]
        public presedens[] presedens {
            get {
                return this.presedensField;
            }
            set {
                this.presedensField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog")]
    public enum journalposttype {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Inngående dokument")]
        Inngåendedokument,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Utgående dokument")]
        Utgåendedokument,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Organinternt dokument for oppfølging")]
        Organinterntdokumentforoppfølging,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Organinternt dokument uten oppfølging")]
        Organinterntdokumentutenoppfølging,
        
        /// <remarks/>
        Saksframlegg,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/metadatakatalog")]
    public enum journalstatus {
        
        /// <remarks/>
        Journalført,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Ferdigstilt fra saksbehandler")]
        Ferdigstiltfrasaksbehandler,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Godkjent av leder")]
        Godkjentavleder,
        
        /// <remarks/>
        Ekspedert,
        
        /// <remarks/>
        Arkivert,
        
        /// <remarks/>
        Utgår,
    }
}
