///////////////////////////////////////////////////////////
//  UtgaaendeJournalpost.cs
//  Implementation of the Class UtgaaendeJournalpost
//  Generated by Enterprise Architect
//  Created on:      27-mai-2020 09:36:24
//  Original author: TorKjetilNilsen
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FIKS.eMeldingArkiv.eMeldingForenkletArkiv;
namespace FIKS.eMeldingArkiv.eMeldingForenkletArkiv {
	public class UtgaaendeJournalpost {

		
		//public Avskrivning avskrivning;
		public int journalaar;
		public int journalsekvensnummer;
		public int journalpostnummer;
		//public Journalstatus journalstatus;
		public DateTime? dokumentetsDato;
		/// <summary>
		/// Definisjon: Dato et internt produsert dokument ble sendt/ekspedert
		/// 
		/// Kilde: Registreres manuelt eller automatisk av systemet ved elektronisk
		/// kommunikasjon
		/// 
		/// Kommentar: (ingen)
		/// 
		/// M105 sendtDato
		/// </summary>
		public DateTime? sendtDato;
		public ForenkletDokument hoveddokument;
		/// <summary>
		/// Definisjon: Dato et internt produsert dokument ble sendt/ekspedert
		/// 
		/// Kilde: Registreres manuelt eller automatisk av systemet ved elektronisk
		/// kommunikasjon
		/// 
		/// Kommentar: (ingen)
		/// 
		/// M105 sendtDato
		/// </summary>
		public DateTime? offentlighetsvurdertDato;
		public EksternNøkkel referanseEksternNøkkel;
		public string tittel;
		public List<ForenkletDokument> vedlegg;

		public List<Korrespondansepart> mottaker;
		public List<Korrespondansepart> avsender;

		public List<KorrespondansepartIntern> internAvsender;
		

		public UtgaaendeJournalpost(){
			vedlegg = new List<ForenkletDokument>();
			mottaker = new List<Korrespondansepart>();
			avsender = new List<Korrespondansepart>();
			internAvsender = new List<KorrespondansepartIntern>();
		}

		~UtgaaendeJournalpost(){

		}

	}//end UtgaaendeJournalpost

}//end namespace eMeldingForenkletArkiv